CREATE TABLE eatery_group.bronze.restaurant_ds (
    restaurant_id INT,
    restaurant_name STRING,
    country_code INT,
    city STRING,
    address STRING,
    locality STRING,
    locality_verbose STRING,
    longitude DECIMAL(10,6),
    latitude DECIMAL(10,6),
    cuisines STRING,
    average_cost_for_two INT,
    currency STRING,
    has_table_booking STRING,
    has_online_delivery STRING,
    is_delivering_now STRING,
    switch_to_order_menu STRING,
    price_range INT,
    aggregate_rating DECIMAL(4,2),
    rating_color STRING,
    rating_text STRING,
    votes INT,
    ingestion_timestamp TIMESTAMP,
    source_file STRING
);