CREATE CATALOG IF NOT EXISTS eatery_group;

USE CATALOG eatery_group;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS reporting;